// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RasketsRime.Data;

#nullable disable

namespace RasketsRimeCapstone.Migrations
{
    [DbContext(typeof(RasketsRimeDbContext))]
    partial class RasketsRimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "a601c402-545f-4ba8-869d-6f0968774d58",
                            Name = "User",
                            NormalizedName = "user"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b53fb7b7-765a-41dd-ae6d-ef5e71226518",
                            Email = "admin@neopets.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEK0g1QGt+fF4oz7QzAkHGD6UFBieiX+hupSFlCMnxSTQW05oIxD/O1EMUQYSlQdqog==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2525d451-7435-43f8-aeda-2151c1127741",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "e2731372-eb45-4cc5-9a34-d9711f3642b2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f203f6a6-f8a6-438f-ab81-5c1ab7f134d0",
                            Email = "Schlebethany@neopets.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAdumHZJcXK5nGItNdnKEVnT1Xid5JHfEvzQwAp7omOqCKz2hiIIYDUiAXhtncXeqg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "63b8bdca-9ea7-4827-804a-7238741f3800",
                            TwoFactorEnabled = false,
                            UserName = "Schlebethany"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "e2731372-eb45-4cc5-9a34-d9711f3642b2",
                            RoleId = "a601c402-545f-4ba8-869d-6f0968774d58"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RasketsRime.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EventStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExpectedAttendees")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmitedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 6,
                            EventDescription = "Just some rowdy gals ready to get totally twisted.",
                            EventName = "Darla Dinkles Bachelorette Party",
                            EventStart = new DateTime(2024, 4, 12, 7, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedAttendees = 15,
                            IsPublic = true,
                            Status = "Approved",
                            SubmitedOn = new DateTime(2024, 1, 12, 5, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2,
                            VenueId = 5
                        });
                });

            modelBuilder.Entity("RasketsRime.Models.EventService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ServiceId");

                    b.ToTable("EventServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 2,
                            EventId = 1,
                            ServiceId = 16
                        });
                });

            modelBuilder.Entity("RasketsRime.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "We will pick up your trash, but we won't be happy about it.",
                            IsActive = true,
                            Price = 60m,
                            ServiceName = "Trash-Pickup"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pitaya, Pineapple, Mango...You name it, we will throw it in a bucket and blend it till its oh-so smooth.",
                            IsActive = true,
                            Price = 100m,
                            ServiceName = "Smoothie-Bar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "If your wondering who will be providing security, chances are you've already met them and they were likely not impressed. Ever watchful, they do not rest.",
                            IsActive = true,
                            Price = 100m,
                            ServiceName = "Security (By The Arbiter's Secret Militia)"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Just because a shadowy organization strong-armed our town into a monopoly on security services does NOT mean they don't make excellent caregivers. Our operatives are standing by to assess and neutralize any bad behavior.",
                            IsActive = true,
                            Price = 200m,
                            ServiceName = "Child-Care (Also By The Arbiter's Secret Militia)"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Look, the University is under the lake. You want to try your hand at getting your car out yourself? Go ahead.",
                            IsActive = true,
                            Price = 50m,
                            ServiceName = "Valet-Lake Parking"
                        },
                        new
                        {
                            Id = 6,
                            Description = "We will let you shove as many books as you can fit in a burlap sac from the 'donated' stacks. We are not responsible for what these books may or may not do upon reading. ",
                            IsActive = true,
                            Price = 800m,
                            ServiceName = "Library 'Supermarket Sweep'"
                        },
                        new
                        {
                            Id = 7,
                            Description = "It gets cold here. These floating bowls of heat will warm your guests. Be sure you do not put ANYTHING in the censor. Again we cannot stress that enough.",
                            IsActive = true,
                            Price = 20m,
                            ServiceName = "Mobile Heat Censors"
                        },
                        new
                        {
                            Id = 8,
                            Description = "You really do not want to try parking up here. The lift will get you from the main square in town all the way up to the Station. Be sure to dress warmly!",
                            IsActive = true,
                            Price = 10m,
                            ServiceName = "Mountain-Top Ski Lift"
                        },
                        new
                        {
                            Id = 9,
                            Description = "We know. You think you are the gift of song itself. Why not put your money where your mouth is? Let the whole town hear your...choices by selecting the music.",
                            IsActive = true,
                            Price = 100m,
                            ServiceName = "'Are You The DJ?'"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Everyone thinks they are a Snow White. Now it can finally be true for you. Many tiny cuddles and helpful forest friends are waiting for you to add this package.",
                            IsActive = true,
                            Price = 80m,
                            ServiceName = "Woodland Creature Package"
                        },
                        new
                        {
                            Id = 11,
                            Description = "The trees are ancient, yet the Ents are older still. Take a walk with several of these arboreal protectors and see the world through a whole new lens.",
                            IsActive = true,
                            Price = 50m,
                            ServiceName = "Ent Walk"
                        },
                        new
                        {
                            Id = 12,
                            Description = "You know when you think something is going to be really funny, but then it just creeps everyone out? Yeah...we got you. Your guests will be terrified. So will you, actually.",
                            IsActive = true,
                            Price = 20m,
                            ServiceName = "Suddenly Spooky"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The tiles in this space can be made to display a mind-melting fractal of the person standing on them. Now just imagine you have 200 guests...yeah, we thought you would like that.",
                            IsActive = true,
                            Price = 80m,
                            ServiceName = "Fractal Tile"
                        },
                        new
                        {
                            Id = 14,
                            Description = "We weren't kidding when we said they built the Cathedral right on top the Goofy Golf. With access to the subterranean levels, your golf skills will be tested. You will be tested. ",
                            IsActive = true,
                            Price = 200m,
                            ServiceName = "Goofy Golf"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The lilting voices of those gone before will be piped in to punctuate the ethereal nature of this space.",
                            IsActive = true,
                            Price = 200m,
                            ServiceName = "Haunting Vocals"
                        },
                        new
                        {
                            Id = 16,
                            Description = "When you want to have a party but don't want to risk bringing anything back from the other side. Madam Zostra will gladly hold back her services so that you might feel more comfortable in your mortal vessel.",
                            IsActive = true,
                            Price = 500m,
                            ServiceName = "Non-Seance"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Madam Zostra is a skilled Translocator. She can have you zipped up to the Poconos all without leaving the warmth of her cottage.",
                            IsActive = true,
                            Price = 600m,
                            ServiceName = "Astral Travel"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Found an object of dubious origin? Worried it might be cursed? This is like Antiques Roadshow but if that old spoon set made you end every sentence with a question.",
                            IsActive = true,
                            Price = 200m,
                            ServiceName = "Item Identification"
                        },
                        new
                        {
                            Id = 19,
                            Description = "It is uhh, loud here. You will probably need these. Your guests will also be wanting these.",
                            IsActive = true,
                            Price = 20m,
                            ServiceName = "Earplugs"
                        },
                        new
                        {
                            Id = 20,
                            Description = "NO, these are not the same lasers they used to etch this space from the quarry. They have had fun colors added. You will probably not be in any danger.",
                            IsActive = true,
                            Price = 300m,
                            ServiceName = "Laser Lights"
                        },
                        new
                        {
                            Id = 21,
                            Description = "What can we can? They're REALLY big balloons.",
                            IsActive = true,
                            Price = 200m,
                            ServiceName = "Comically Large Baloon Drop"
                        });
                });

            modelBuilder.Entity("RasketsRime.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Roles")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "101 Main Street",
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            IsAdmin = true,
                            LastName = "Strator",
                            ProfileImage = "https://i.pinimg.com/564x/c0/fd/d7/c0fdd735d4db94c60866e43e44ae98cf.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "222 N Sidereal Way",
                            FirstName = "Schlebethany",
                            IdentityUserId = "e2731372-eb45-4cc5-9a34-d9711f3642b2",
                            IsAdmin = false,
                            LastName = "Pleasance",
                            ProfileImage = "https://beta.creativecirclecdn.com/timberjay/original/20210127-160305-1.29%20weasel%20looks.tif.jpg"
                        });
                });

            modelBuilder.Entity("RasketsRime.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "19 Under Lake Blvd",
                            ContactInfo = "Arbiter Darling : 850-474-5555",
                            Description = "A prestigious arcane academy lovingly nestled beneath the central lake of the town. Its atrium is more than accommodating for crowds large and small.",
                            IsActive = true,
                            MaxOccupancy = 300,
                            VenueName = "The Unmoored University"
                        },
                        new
                        {
                            Id = 2,
                            Address = "327 Rumbler Route Way",
                            ContactInfo = "Foxglove Mackenzie -- 850-985-2934",
                            Description = "From atop the mountains, the radio station glows eternal. Deceptively large, its unassuming facade belies the many cozy suites nestled within its walls.",
                            IsActive = true,
                            MaxOccupancy = 85,
                            VenueName = "Mountain-Top Radio Station"
                        },
                        new
                        {
                            Id = 3,
                            Address = "667 W Rambling Road",
                            ContactInfo = "Thorely Goodparty",
                            Description = "The warmth and glow of the Cedrine trees provides a lovely backdrop for any event. Weather can be controlled from inside. Many a night has been spent taking in the thrum of the woods under a revelry-drunk moon.",
                            IsActive = true,
                            MaxOccupancy = 50,
                            VenueName = "Cedrine Forest Adirondack"
                        },
                        new
                        {
                            Id = 4,
                            Address = "3762 Gnomiad Fork",
                            ContactInfo = "Parker Billian -- 850-987-2926",
                            Description = "Believe it or not, this was never a cathedral. The creator instead saw fit to erect this behemoth of architectural ego on top of the abandoned Goofy Golf complex. Vestigial dinosaurs and aliens still linger where you would least expect them.",
                            IsActive = true,
                            MaxOccupancy = 200,
                            VenueName = "Glinterland Cathedral Hall"
                        },
                        new
                        {
                            Id = 5,
                            Address = "3 Nestledown Thicket",
                            ContactInfo = "Madame Zostra -- 850-222-1053",
                            Description = "Ambience and incense will greet you as you settle in. On display are the relics and spoils of war won by Madame Zostra in her pursuit of the Thaumaturgical Arts",
                            IsActive = true,
                            MaxOccupancy = 20,
                            VenueName = "Madame Zostra's Family Fun Time Seance Parlor"
                        },
                        new
                        {
                            Id = 6,
                            Address = "5590 Fingerpail Row",
                            ContactInfo = "Maisel Darby --850-334-9010",
                            Description = "Much like its namesake, this amphitheatre is beloved and commands your attention. Excellent acoustics make for a wonderful way to talk/sing at your audience.  ",
                            IsActive = true,
                            MaxOccupancy = 500,
                            VenueName = "The Patty Lupone Groupon Coupon Main Stage"
                        });
                });

            modelBuilder.Entity("RasketsRime.Models.VenueService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ServiceId = 1,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            ServiceId = 2,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            ServiceId = 3,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            ServiceId = 4,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 5,
                            ServiceId = 1,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 6,
                            ServiceId = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 7,
                            ServiceId = 3,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 8,
                            ServiceId = 4,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 9,
                            ServiceId = 1,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 10,
                            ServiceId = 2,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 11,
                            ServiceId = 3,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 12,
                            ServiceId = 4,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 13,
                            ServiceId = 1,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 14,
                            ServiceId = 2,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 15,
                            ServiceId = 3,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 16,
                            ServiceId = 4,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 17,
                            ServiceId = 1,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 18,
                            ServiceId = 2,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 19,
                            ServiceId = 3,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 20,
                            ServiceId = 4,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 21,
                            ServiceId = 1,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 22,
                            ServiceId = 2,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 23,
                            ServiceId = 3,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 24,
                            ServiceId = 4,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 25,
                            ServiceId = 5,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 26,
                            ServiceId = 6,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 27,
                            ServiceId = 7,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 28,
                            ServiceId = 8,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 29,
                            ServiceId = 9,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 30,
                            ServiceId = 10,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 31,
                            ServiceId = 11,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 32,
                            ServiceId = 12,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 33,
                            ServiceId = 13,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 34,
                            ServiceId = 14,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 35,
                            ServiceId = 15,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 36,
                            ServiceId = 16,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 37,
                            ServiceId = 17,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 38,
                            ServiceId = 18,
                            VenueId = 5
                        },
                        new
                        {
                            Id = 39,
                            ServiceId = 19,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 40,
                            ServiceId = 20,
                            VenueId = 6
                        },
                        new
                        {
                            Id = 41,
                            ServiceId = 21,
                            VenueId = 6
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RasketsRime.Models.Event", b =>
                {
                    b.HasOne("RasketsRime.Models.UserProfile", "UserProfile")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasketsRime.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("RasketsRime.Models.EventService", b =>
                {
                    b.HasOne("RasketsRime.Models.Event", null)
                        .WithMany("EventServices")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasketsRime.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("RasketsRime.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("RasketsRime.Models.VenueService", b =>
                {
                    b.HasOne("RasketsRime.Models.Service", "Service")
                        .WithMany("VenueServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RasketsRime.Models.Venue", "Venue")
                        .WithMany("VenueServices")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("RasketsRime.Models.Event", b =>
                {
                    b.Navigation("EventServices");
                });

            modelBuilder.Entity("RasketsRime.Models.Service", b =>
                {
                    b.Navigation("VenueServices");
                });

            modelBuilder.Entity("RasketsRime.Models.UserProfile", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RasketsRime.Models.Venue", b =>
                {
                    b.Navigation("VenueServices");
                });
#pragma warning restore 612, 618
        }
    }
}
